### PR TITLE
Etc. -> E.g.

### PR DESCRIPTION
**Pull request by SwissalpS**
The way I see this, it's an example not etcetera.

### CODE REVIEW

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by OgelGames** [comment]
Makes sense :+1:

**Comment by S-S-X** [comment]
Seems fine but also there seemed to be multiple other small issues around this line / in same group. Could PR those too while it is in fresh memory.

**Comment by SwissalpS** [comment]
Like "max\_charge"?
Please go ahead, if you have the time to revise the entire doc :D

**Comment by S-S-X** [comment]
> Like "max_charge"? Please go ahead, if you have the time to revise the entire doc :D

Yeah had little things like that in mind, was just a bit too late to add here. Maybe this is still best place for discussion / opinions:
* maxcharge -> max_charge
* `charge`, `max_charge`
* Callback -> Function. This is debatable, these are callbacks even if not the same as usual caller initiated async responses.
* Have to -> Must or Should. Pretty straightforward IMO.

**Comment by SwissalpS** [comment]
"max\\_charge" was what I meant. the '\' didn't show up.

**Comment by S-S-X** [comment]
> "max\_charge" was what I meant. the '\' didn't show up.

While \ isn't hard requirement there it is still kinda appropriate to escape md but still should probably instead be `code` and rest of maxcharge should probably be max_charge too.

**Pull request merged**
