### PR TITLE
prospectors as per h-v-smacker

### PR DESCRIPTION
**Pull request by imre84**
I believe this to be a decent rework of h-v-smacker's prospectors

### CODE REVIEW

**Comment by S-S-X** [comment]
Few luacheck complaints:
```
Checking technic/materials.lua                    2 warnings

    technic/materials.lua:70:2: value assigned to field mithril_block is overwritten on line 74 before use
    technic/materials.lua:73:121: line is too long (123 > 120)

Checking technic/tools/prospector.lua             7 warnings

    technic/tools/prospector.lua:134:9: unused variable ignoreme
    technic/tools/prospector.lua:136:9: unused variable look_diameter
    technic/tools/prospector.lua:154:121: line is too long (158 > 120)
    technic/tools/prospector.lua:179:121: line is too long (186 > 120)
    technic/tools/prospector.lua:182:121: line is too long (171 > 120)
    technic/tools/prospector.lua:190:9: unused variable ignoreme
    technic/tools/prospector.lua:200:9: unused variable look_diameter
```
Good to get rid of unused variables and unnecessary assignments (overwrite before use).
Line too long is just about formatting, simply break it down to multiple lines.

For items not sure about technic:control_logic_unit_adv, is it needed or could prospector mk2 just use prospector and few existing upgrade items for recipe?
I mean only use for technic:control_logic_unit_adv seems to be prospector recipe and it would be only available if prospector is enabled.

For device / functionality didn't test or read code that well yet but there seems to be at least some typos in tool definition fields.

For now I wont be against adding directly to technic mod, this has been more a future development suggestion:
Generally, in my opinion, it could be better to move new tools to new mods (also at some point start moving some existing tools away from technic modpack into their own mods).

**Comment by imre84** [comment]
1 typo of max_charge vs max_xharge found

**Comment by imre84** [comment]
> Generally, in my opinion, it could be better to move new tools to new mods (also at some point start moving some existing tools away from technic modpack into their own mods).

do you mean mods inside technic modpack or completely separate? I believe there are at least 3 versions of the technic modpack that have at least some traction. would dissecting everything into smaller mods mean fewer versions of mods? I like the prospectors from Smacker's version, however I like the fact that there are protected chests in this version.

do you think it is possible to achieve a grand unified technic modpack? if so that would mean more volunteers/manpower working for everyone's benefit

linux forks server is under no circumstances willing to use basic materials mod, so if we want to make a grand unification we need to make basic materials an optional dependency. also, they want to keep their old recipes (so that the factories built by players don't get broken by upgrades). so maybe crafts need to be in a crafts.lua and then have everybody rebase their version of crafts.lua on top of the unified master branch

**Comment by OgelGames** [comment]
Personally I'd prefer to see the prospector get reworked and improved instead of adding a MK2 version.

**Comment by imre84** [comment]
ok so how do we proceed from here?

**Comment by S-S-X** [comment]
For kind of like Mk2 version prospector but same tool one could also use upgrade slot where you'd have to put some thing to gain access to more features. Could well be memory chip (possibly with info for multiple nodes stored in it) and possibly even second upgrade for some other things.

**Comment by imre84** [comment]
ok I believe this PR will be going nowhere. Can we reject it then?

**Comment by S-S-X** [comment]
Just in case gh cleans it up and we'd like to continue with this here's patch for this

<details><summary>Patch</summary>

```patch
From a9588d4834e6ccfa4101672a613076c021c4392f Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Imre=20P=C3=A9ntek?= <pentek.imre@gmail.com>
Date: Fri, 29 Mar 2024 12:06:17 +0100
Subject: [PATCH 1/3] prospectors as per h-v-smacker

---
 technic/materials.lua                         |   3 +
 .../textures/pipeworks_teleport_tube_inv.png  | Bin 0 -> 842 bytes
 .../technic_control_logic_unit_adv.png        | Bin 0 -> 623 bytes
 technic/textures/technic_prospector_mk2.png   | Bin 0 -> 391 bytes
 technic/tools/prospector.lua                  | 208 ++++++++++++++++--
 5 files changed, 192 insertions(+), 19 deletions(-)
 create mode 100644 technic/textures/pipeworks_teleport_tube_inv.png
 create mode 100644 technic/textures/technic_control_logic_unit_adv.png
 create mode 100644 technic/textures/technic_prospector_mk2.png

diff --git a/technic/materials.lua b/technic/materials.lua
index bd381055..f8bbb161 100644
--- a/technic/materials.lua
+++ b/technic/materials.lua
@@ -69,5 +69,8 @@ technic.materials = {
 	mithril_ingot = has_moreores and "moreores:mithril_ingot" or has_mcl and "mcl_core:lapis" or "default:steel_ingot",
 	silver_ingot = has_moreores and "moreores:silver_ingot" or has_mcl and "mcl_core:gold_ingot" or "default:gold_ingot",
 	pick_silver = has_moreores and "moreores:pick_silver" or has_mcl and "mcl_tools:pick_gold" or "default:gold_pickaxe",
+    pick_mithril = has_moreores and "moreores:pick_mithril" or
+                   has_mcl      and "mcl_tools:pick_diamond" or
+                                    "default:pick_diamond",
 	mithril_block = has_moreores and "moreores:mithril_block" or has_mcl and "mcl_core:lapisblock" or "default:goldblock",
 }
diff --git a/technic/textures/pipeworks_teleport_tube_inv.png b/technic/textures/pipeworks_teleport_tube_inv.png
new file mode 100644
index 0000000000000000000000000000000000000000..d12b896bb6568445eb525ebd1fe6b9ec2b4ca48e
GIT binary patch
literal 842
zcmbV~{Zq>U9LK-gv}&3t2}Mu#15SB7Me!|7b+j9Hhg~%6Je@lg$CQWfl&huAjh<_T
zq-ECZ#!{BPlJqU+>99Nwr%RWI*uD>wKIUKWzI(r4zr26=+~?jZu_%epo6bWJgrAa}
zxZX|lpS?Kl)U+sv-DnoCl?YwdPGD|<^AtEv0MiOgyQ}ZEi?Dz*m%)wT%m?RbppBHi
zlDtp|j0tFitNSK6RY0n#OT|ow0q7>O5(BysXg$+u0;++$SVU>hfwP#>l~avs>Pjh4
z)j;cjst58MkY|{7J=4}iHJqW1wLq5BEti2TWi0MO9n;zfl!m^35vU8a`4WAthHkE+
zP3M8Ebf5g>r_V$;mK|I#+5rD6WGN2r$FL`*B*se=tgkN#QAE5C_Mv~5?Qn8}*Q_t!
z9JiyK9dP>Lod#`q^v#9$@A%CL88j4SzUd7dTd+b2ep>L^+4J$%XtF&(RsD4xzN5IS
z>)TYBhnO8#6T&)(j&QGjsNmHaN4PSJvNSkrWvqft6+0$KkF@>ZWMPpWt1(_=JGQOv
z9?~-3&an)ermM#Jh90ea`96JMWOJI+T)sFP|MONT%MqXVEczYO6Qfo==FGt5tG^@)
z1&?$}_SqlAyZulduveBb6vZ-c->W2uB;*ik;6}C?HyOHh`TNqIXXS9?r1s}TIkyb$
z^OxEm5*xA$Fl~}|UPDd%oOYWGk(S^$f{C$3vB`mk5;P)caiDM@4DneO+UebtJ+F{g
zvGC1U-v~ci=;6q(`jg{VAZB%ZwoUk*D&dTVuJY(P(3CmwzDFe0VpC*g;hEoup9M`u
zcO2LlVJ@AG4c*;rm6rwJd(w(b*VmZ!ds3%~tTPn}oDzNzyVdad9iq|fmZ0R=7P-zg
zi1igPR;l2aS4}_hf~EOot-Je*RPzMl!_jKbLs$6HP@LZ%{<B_><tp;l1<%VEZ+ZP`
zyaPA*nxC?L@nA{L(zfN2*SX90T@A|<Y(;O#D^gx1$puS}qt^HbgR#og-nssGSz$(?
u-Fx`>*4X>0>G$3$G)LoNV6^v_H{F%)Uy*Hd)mw(#6GKvjqQvF|*~!17+S(KV

literal 0
HcmV?d00001

diff --git a/technic/textures/technic_control_logic_unit_adv.png b/technic/textures/technic_control_logic_unit_adv.png
new file mode 100644
index 0000000000000000000000000000000000000000..d5508d51ebb288670b479c598f7f53a96f94a78b
GIT binary patch
literal 623
zcmV-#0+9WQP)<h;3K|Lk000e1NJLTq000mG000mO1^@s6AM^iV00006VoOIv0RI60
z0RN!9r;`8x010qNS#tmY3ljhU3ljkVnw%H_000McNliru;sX;7D;WLO+Pwe(0sKis
zK~y-)t&>kkR8bhkfA{&GPhkodfg(cxD2R4JYgbW5(56<=5aCAJG>h68hLJ>zq{dJZ
zA&5{+C})Pi7BdsoCMhToDk;Vq21J5!pmE-N_r3SEcs5BXCHTSR9`3#8@SVf`U@Pj`
z=!H#lW~Z)2;Nz=V048pnX&p-(i3BG{816YlTEv)p_a>I?KEV4=5)%<)@Z4TzCZ<~f
zo<5xVtyst$56i`zEKlsAkm(A`#hg?g@1~HB@bXM23z;sjT+B%&f1=J)`R8vNN~L-K
z%jXh0KpHJW`P!vc^TcYjRT#K9jwcOPvoe*#kE$b~*lPd29V8M7)6BleTH7r}>gpw0
z0An4$f1WJ@2k#^SEOT+GB+YH@v;Zxj*1X#g$AFsF0Af^@zT-Nz`fd1+^{c#9juH48
zt@XOCZ&U{0`$2^5po-`Fn-T!f678n%xyp4Me82-)<M%IYL^dP@rB_y>K!y^h&H121
zfBjY_^sCa;WGPo0Xm>?y+f+Je!1o-nEJKMh@El)4(Q4<eHrlt@F#vi8<~kNKT~aRQ
z<U#*Q3h85ExtNpmP`r+__j~Fe>GhK<^!1K+05E*(HUN{CJ4wcE03KcM<KB4-fc*G0
zBWEEqJOIF0cN3!*4+C(se{~*S-aT3m=R+#~Um>OjPi@H{^AiiT_r)Aa3wQtk002ov
JPDHLkV1gko5$ON`

literal 0
HcmV?d00001

diff --git a/technic/textures/technic_prospector_mk2.png b/technic/textures/technic_prospector_mk2.png
new file mode 100644
index 0000000000000000000000000000000000000000..e255dd757be37f03bbcd7219ac4e346c1f748260
GIT binary patch
literal 391
zcmeAS@N?(olHy`uVBq!ia0vp^3LwnE1|*BCs=fdzwj^(N7l!{JxM1({$v_d#0*}aI
z1_o|n5N2eUHAey{$X?><>&pI!gPB3jYWW4BYz78K5l<J#kch)?r|lGMHV|<AZ!~2A
z6Gsf!6O)H0I=vMOU4)+mbTM-UaL(Jv%zrpBa&>a5>OG#ehxRYuv$h-&^-t;EzoS6p
zgv?DwulfDASKYd4aK`v3(}ezt#b4juT@hl!(%R+iD5ChNcCXd-jK7J#KX_%l*2-$#
zICB27@-MXv^?Pg2-#NKdfot*(O^c5oWKL-OV|($#%c9G(b8~9NndW_Zk%jkd7R-=i
zV3;1v%dq3_as`fU{5+q176-lQ7ZbRD?}15Aj==57>T_9_C8lgXcC~AT<DsYR+%8`%
zdRrAbqvF<VY^-Sp235JVw^F{N3!{^cAp3__52gpq6LYl7-Y&R#?b8#n9eJ0(bYIR>
iR0;c;z;U^yhVi@nmMM%gX6yzA8H1;*pUXO@geCyKq?+jf

literal 0
HcmV?d00001

diff --git a/technic/tools/prospector.lua b/technic/tools/prospector.lua
index 0d96de07..e060d864 100644
--- a/technic/tools/prospector.lua
+++ b/technic/tools/prospector.lua
@@ -64,9 +64,7 @@ technic.register_power_tool("technic:prospector", {
 		return toolstack
 	end,
 	on_place = function(toolstack, user, pointed_thing)
-		if not user or not user:is_player() or user.is_fake_player then
-			return
-		end
+		if not user or not user:is_player() or user.is_fake_player then return end
 		local meta = toolstack:get_meta()
 		local target = meta:get("target") or migrate_meta(meta)
 		local look_depth, look_radius = get_field(meta)
@@ -112,36 +110,208 @@ technic.register_power_tool("technic:prospector", {
 	end,
 })
 
-minetest.register_on_player_receive_fields(function(user, formname, fields)
-	if formname ~= "technic:prospector_control" then
-		return false
+local function remove_waypoints(user, w)
+
+	for i,p in ipairs(w) do
+		user:hud_remove(p)
 	end
-	if not user or not user:is_player() or user.is_fake_player then
+
+end
+
+technic.register_power_tool("technic:prospector_mk2", {
+	description = S("Prospector Mk2"),
+	inventory_image = "technic_prospector_mk2.png",
+	max_charge = 650000,
+	on_use = function(toolstack, user, pointed_thing)
+		if not user or not user:is_player() or user.is_fake_player then return end
+		if pointed_thing.type ~= "node" then return end
+		local meta = toolstack:get_meta()
+		local target = meta:get("target") or migrate_meta(meta)
+		if not target then
+			minetest.chat_send_player(user:get_player_name(), S("Right-click to set target block type"))
+			return toolstack
+		end
+		local _, look_radius = get_field(meta)
+		look_radius = look_radius * 7
+		local charge_to_take = math.pow(look_radius, 3)
+		if not technic.use_RE_charge(toolstack, charge_to_take) then
+			return toolstack
+		end
+		local start_pos = pointed_thing.under
+
+		local min_pos = {x = start_pos.x - look_radius, y = start_pos.y - look_radius, z = start_pos.z - look_radius }
+
+		local max_pos = {x = start_pos.x + look_radius, y = start_pos.y + look_radius, z = start_pos.z + look_radius }
+
+		local results = minetest.find_nodes_in_area(min_pos, max_pos, target)
+
+		local waypoints = {}
+		local found = false
+
+		if #results > math.pow(look_radius, 3) * 0.25 then
+
+			minetest.chat_send_player(user:get_player_name(), S("@1 is literally everywhere within the scanned region",
+																minetest.registered_nodes[target].description))
+
+		else
+
+			for _,p in ipairs(results) do
+
+				if math.random() >= 0.02 then
+					found = true
+					local idx = user:hud_add({
+						hud_elem_type = "waypoint",
+						name = "",
+						text = "",
+						number = 0xFF0000,
+						world_pos = p
+					})
+					table.insert(waypoints, idx)
+
+				end
+
+			end
+
+			if found then
+				minetest.after(7, remove_waypoints, user, waypoints)
+			end
+
+			minetest.chat_send_player(user:get_player_name(), S("@1 is " .. (found and "present" or "absent") ..
+																" within @2 meters radius",
+																minetest.registered_nodes[target].description,
+																look_radius))
+		end
+
+		minetest.sound_play("technic_prospector_" .. (found and "hit" or "miss"),
+							{ pos = vector.add(user:getpos(), { x = 0, y = 1, z = 0 }),
+							  gain = 1.0,
+							  max_hear_distance = 10})
+
+		return toolstack
+	end,
+	on_place = function(toolstack, user, pointed_thing)
+		if not user or not user:is_player() or user.is_fake_player then return end
+		local meta = toolstack:get_meta()
+		local target = meta:get("target") or migrate_meta(meta)
+		local _, look_radius = get_field(meta)
+		look_radius = look_radius * 7
+		local pointed
+		if pointed_thing.type == "node" then
+			local pname = minetest.get_node(pointed_thing.under).name
+			local pdef = minetest.registered_nodes[pname]
+			if pdef and (pdef.groups.not_in_creative_inventory or 0) == 0 and pname ~= target then
+				pointed = pname
+			end
+		end
+
+		minetest.show_formspec(user:get_player_name(), "technic:prospector_control_mk2",
+			"size[7,8.5]"..
+			"item_image[0,0;1,1;"..toolstack:get_name().."]"..
+			"label[1,0;"..minetest.formspec_escape(toolstack:get_description()).."]"..
+			(target and
+				"label[0,1.5;Current target:]"..
+				"label[0,2;"..minetest.formspec_escape(minetest.registered_nodes[target].description).."]"..
+				"item_image[0,2.5;1,1;"..target.."]" or
+				"label[0,1.5;"..S("No target set").."]")..
+			(pointed and
+				"label[3.5,1.5;"..S("May set new target:").."]"..
+				"label[3.5,2;"..minetest.formspec_escape(minetest.registered_nodes[pointed].description).."]"..
+				"item_image[3.5,2.5;1,1;"..pointed.."]"..
+				"button_exit[3.5,3.65;2,0.5;target_"..pointed..";"..S("Set target").."]" or
+				"label[3.5,1.5;"..S("No new target available").."]")..
+			"label[0,4.5;Scan radius:]"..
+			"label[0,5;".. look_radius .."]"..
+			"label[3.5,4.5;Set scan radius:]"..
+			"button_exit[3.5,5.15;1,0.5;look_radius_1;7]"..
+			"button_exit[4.5,5.15;1,0.5;look_radius_2;14]"..
+			"button_exit[5.5,5.15;1,0.5;look_radius_3;21]"..
+			"label[0,7.5;"..S("Accuracy:").."]"..
+			"label[0,8;98%]")
 		return
-	end
+	end,
+})
+
+minetest.register_on_player_receive_fields(function(user, formname, fields)
+	if formname ~= "technic:prospector_control" and formname ~= "technic:prospector_control_mk2" then return false end
+	if not user or not user:is_player() or user.is_fake_player then return end
 	local toolstack = user:get_wielded_item()
-	if toolstack:get_name() ~= "technic:prospector" then
+
+	if formname == "technic:prospector_control" and toolstack:get_name() == "technic:prospector" then
+		local meta = toolstack:get_meta()
+		for field, value in pairs(fields) do
+			if field:sub(1, 7) == "target_" then
+				meta:set_string("target", field:sub(8))
+			elseif field:sub(1, 12) == "look_radius_" then
+				meta:set_int("look_radius", field:sub(13))
+			elseif field:sub(1, 11) == "look_depth_" then
+				meta:set_int("look_depth", field:sub(12))
+			end
+		end
+		user:set_wielded_item(toolstack)
 		return true
 	end
-	local meta = toolstack:get_meta()
-	for field, value in pairs(fields) do
-		if field:sub(1, 7) == "target_" then
-			meta:set_string("target", field:sub(8))
-		elseif field:sub(1, 12) == "look_radius_" then
-			meta:set_int("look_radius", field:sub(13))
-		elseif field:sub(1, 11) == "look_depth_" then
-			meta:set_int("look_depth", field:sub(12))
+
+	if formname == "technic:prospector_control_mk2" and toolstack:get_name() == "technic:prospector_mk2" then
+		local meta = toolstack:get_meta()
+		for field, value in pairs(fields) do
+			if field:sub(1, 7) == "target_" then
+				meta:set_string("target", field:sub(8))
+			elseif field:sub(1, 12) == "look_radius_" then
+				meta:set_int("look_radius", field:sub(13))
+			end
 		end
+		user:set_wielded_item(toolstack)
+		return true
 	end
-	user:set_wielded_item(toolstack)
+
 	return true
 end)
 
+if not minetest.registered_items["pipeworks:teleport_tube_1"] then
+	-- in case the teleporting tube is disabled in pipeworks:
+	minetest.register_craftitem('technic:teleport_tube_1', {
+		description = "Teleporting Pneumatic Tube Segment (disabled)",
+		inventory_image = "pipeworks_teleport_tube_inv.png",
+	})
+	minetest.register_alias("pipeworks:teleport_tube_1", "technic:teleport_tube_1")
+	minetest.register_craft({
+		output = 'technic:teleport_tube_1',
+		recipe = {
+			{technic.materials.mese_crystal, 'technic:copper_coil', technic.materials.mese_crystal},
+			{'pipeworks:tube_1', 'technic:control_logic_unit', 'pipeworks:tube_1'},
+			{technic.materials.mese_crystal, 'technic:copper_coil', technic.materials.mese_crystal},
+		}
+	})
+end
+
 minetest.register_craft({
 	output = "technic:prospector",
 	recipe = {
-		{mat.pick_silver, mat.mithril_block, "pipeworks:teleport_tube_1"},
+		{mat.pick_silver, "default:goldblock", "pipeworks:teleport_tube_1"},
 		{"basic_materials:brass_ingot", "technic:control_logic_unit", "basic_materials:brass_ingot"},
+		{"", "technic:red_energy_crystal", ""},
+	}
+})
+
+minetest.register_craftitem( "technic:control_logic_unit_adv", {
+	description = S("Advanced Control Logic Unit"),
+	inventory_image = "technic_control_logic_unit_adv.png",
+})
+
+minetest.register_craft({
+	output = 'technic:control_logic_unit_adv',
+	recipe = {
+		{'','technic:control_logic_unit',''},
+		{'','default:tin_ingot',''},
+		{'','technic:control_logic_unit',''}
+	}
+})
+
+minetest.register_craft({
+	output = "technic:prospector_mk2",
+	recipe = {
+		{mat.pick_mithril, mat.mithril_block, "pipeworks:teleport_tube_1"},
+		{"basic_materials:brass_ingot", "technic:control_logic_unit_adv", "basic_materials:brass_ingot"},
 		{"", "technic:blue_energy_crystal", ""},
 	}
 })

From 3677edb1306168a20146874da4988b57bb5c0c8a Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Imre=20P=C3=A9ntek?= <pentek.imre@gmail.com>
Date: Thu, 4 Apr 2024 19:16:57 +0200
Subject: [PATCH 2/3] whitespace fix

---
 technic/materials.lua | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/technic/materials.lua b/technic/materials.lua
index f8bbb161..62158da3 100644
--- a/technic/materials.lua
+++ b/technic/materials.lua
@@ -69,8 +69,8 @@ technic.materials = {
 	mithril_ingot = has_moreores and "moreores:mithril_ingot" or has_mcl and "mcl_core:lapis" or "default:steel_ingot",
 	silver_ingot = has_moreores and "moreores:silver_ingot" or has_mcl and "mcl_core:gold_ingot" or "default:gold_ingot",
 	pick_silver = has_moreores and "moreores:pick_silver" or has_mcl and "mcl_tools:pick_gold" or "default:gold_pickaxe",
-    pick_mithril = has_moreores and "moreores:pick_mithril" or
-                   has_mcl      and "mcl_tools:pick_diamond" or
-                                    "default:pick_diamond",
+	pick_mithril = has_moreores and "moreores:pick_mithril" or
+				   has_mcl      and "mcl_tools:pick_diamond" or
+				                    "default:pick_diamond",
 	mithril_block = has_moreores and "moreores:mithril_block" or has_mcl and "mcl_core:lapisblock" or "default:goldblock",
 }

From 50a622781ce5bcfe2cc6589d2f355681b0496e14 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Imre=20P=C3=A9ntek?= <pentek.imre@gmail.com>
Date: Thu, 4 Apr 2024 19:20:52 +0200
Subject: [PATCH 3/3] whitespace fix

---
 technic/materials.lua | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/technic/materials.lua b/technic/materials.lua
index 62158da3..22b456e7 100644
--- a/technic/materials.lua
+++ b/technic/materials.lua
@@ -70,7 +70,7 @@ technic.materials = {
 	silver_ingot = has_moreores and "moreores:silver_ingot" or has_mcl and "mcl_core:gold_ingot" or "default:gold_ingot",
 	pick_silver = has_moreores and "moreores:pick_silver" or has_mcl and "mcl_tools:pick_gold" or "default:gold_pickaxe",
 	pick_mithril = has_moreores and "moreores:pick_mithril" or
-				   has_mcl      and "mcl_tools:pick_diamond" or
-				                    "default:pick_diamond",
+	               has_mcl      and "mcl_tools:pick_diamond" or
+	                                "default:pick_diamond",
 	mithril_block = has_moreores and "moreores:mithril_block" or has_mcl and "mcl_core:lapisblock" or "default:goldblock",
 }
 ```
 </details>

**Comment by Athozus** [comment]
Imho we can do reopen (maybe by re-creating the branch with the same name it could work) ?

The topic could be changed, but maybe a function like `technic.register_prospector()` with params like `range`, `power`, etc. ?

That is a good thing imho.

**Comment by S-S-X** [comment]
For `technic.register_prospector()` just please no. It just doesn't make sense to pollute API with too specific things.
I mean it would be like adding `minetest.register_stone_node(...)` which might sound good as there's a lot of common properties for all different stone nodes but also it doesn't make sense for API because it is way too specific.

Sure you will find stuff like this if you look for it but that doesn't mean it's good in long run.

If another prospector tool would be registered in same mod then that mod can use its own local function for this.
If that mod wants defaults from Technic prospector then it can `table.copy` prospectors definition.

**Pull request closed without merging**
