### PR TITLE
Few small updates for config/admin commands/cleanup/network lag detection

### PR DESCRIPTION
**Pull request by S-S-X**
* Add / improve admin commands a bit, also moved those command registrations (along with cleanup LBM) to bit better place.
* Moved network specific settings into technic config file.
* Updated network lag detection to use averages instead of last value.
* Some minor cleanup for fixme/todo marked stuff.

### CODE REVIEW

**Comment by S-S-X** [comment]
this will break current behavior for following settings (unless moved to `worldpath/technic.conf` these will revert to defaults):
```
local switch_max_range = tonumber(minetest.settings:get("technic.switch_max_range") or "256")
local off_delay_seconds = tonumber(minetest.settings:get("technic.switch.off_delay_seconds") or "1800")
local overload_reset_time = tonumber(minetest.settings:get("technic.overload_reset_time") or "20")
```
as those are moved to technic configuration file:
https://github.com/mt-mods/technic/blob/fd3353ab73e0b667cf4efc45869f66007aec19bf/technic/config.lua#L1-L27

**Comment by OgelGames** [comment]
Should quarry settings be moved there too? I think it would make sense to have all settings in one place.
https://github.com/mt-mods/technic/blob/c89d0a1305ff6d0d07e153f92b008d86149f24a0/technic/machines/HV/quarry.lua#L6-L8

**Comment by S-S-X** [comment]
> Should quarry settings be moved there too? I think it would make sense to have all settings in one place.

Yes. Actually whole `technic.conf` / `config.lua` was surprise for me too as I tried to place network specific minetest.settings readers to single place grouped into `technic.config` and only after that noticed it actually already exists... :smile:

Pretty sure others missed it too and that's why there's mixed set of configs, well hidden in plain sight.

**Comment by S-S-X** [comment]
Checked rest of it, maybe better to move everything at once, found these grepping for `minetest.settings`:
```
technic_cnc/init.lua:8:                          and minetest.settings:get_bool("technic_cnc_use_technic") ~= false
technic/radiation.lua:349:local enable_radiation_throttling = minetest.settings:get_bool("technic.radiation.enable_throttling")
```

**Comment by S-S-X** [comment]
Did not add CNC (technic_cnc) because that one can be used without technic while technic.conf is handled within technic mod.
I did change config keys to be without dot, of course dot could be added but defaults in `config.lua` stays cleaner if not using it.
Also added one extra underscore for `quarry_max_depth` to match variable name similar to other quarry config keys.

**Comment by S-S-X** [comment]
Also changed `technic.radiation.enable_throttling` to be `enable_radiation_throttling` as that matches other enable* keys and also other radiation enable keys.
`technic` prefix dropped from all config keys as that is not very useful in dedicated config file.

**Review by S-S-X — COMMENTED** [review]
No objections so far and going through changes once again seems good enough.

**Comment by OgelGames** [comment]
Probably should update the settings section in the readme too...

**Comment by S-S-X** [comment]
> Probably should update the settings section in the readme too...

True, should have probably added those changes here, maybe I'll just update those directly in master.

**Pull request merged**
