### PR TITLE
Machines conduct digilines above

### PR DESCRIPTION
**Pull request by OgelGames**

### CODE REVIEW

**Review by BuckarooBanzay — APPROVED** [review]

**Review by eshattow — COMMENTED** [review]
I don't understand how it works but at a quick glance maybe you meant y=1?

**Comment by BuckarooBanzay** [comment]
> I don't understand how it works but at a quick glance but this is a repeat of the existing rule?

Uhm, yeah: it _is_, not sure how 4 eyes could have missed that :facepalm:

**Comment by S-S-X** [comment]
Well, simply just revert but where did idea came from as that was exact rule added long ago? Is there possibly problems with it currently?

**Comment by S-S-X** [comment]
Actually it seems that is to conduct from above, that was left out last intentionally. Don't remember what were reasons....

**Comment by eshattow** [comment]
It seems odd visually for Supply Converter then when power digi cable goes to the input (top) but digiline signal on that power digi cable is not connected to the Supply Converter.

**Comment by OgelGames** [comment]
🤦 

I still think it makes sense for machines to conduct above, because they can be powered from above.

**Comment by S-S-X** [comment]
> It seems odd visually for Supply Converter then when power digi cable goes to the input (top) but digiline signal on that power digi cable is not connected to the Supply Converter.

Yes, there's few machines that should for sure allow connection from above. At least ones that also allow connecting cables from above, but if going with cable connections then for most machines / generic rules machines should not connect digilines from above.

> 🤦
> 
> I still think it makes sense for machines to conduct above, because they can be powered from above.

These are bugs and not meant to work this way.
They can be powered from above because of buggy connections, just did not have time to fix that. There's also no connection overlay textures on top of machines other than pipeworks for some machines.
You can also power machines from front panel but this is also bug and machines should not allow this.

That reasoning is not valid in my opinion as you're basically saying that connection should be allowed because cable connections are also broken.

That said only reason why I did not want to add connection directly above was to avoid problems with excessive messages sent to digiline network where you do not expect those but other than that I'm not against adding connection from above.
Just think how many problems it might cause with current networks in world, how many will contraptions would cause higher digiline usage (and added penalty if connection would be added)? Would it be low enough for it to be acceptable?

**Comment by OgelGames** [comment]
> Just think how many problems it might cause with current networks in world, how many will contraptions would cause higher digiline usage (and added penalty if connection would be added)? Would it be low enough for it to be acceptable?

I think it would be fine, after all this is only to connect machines to digilines, machines don't conduct digilines through themselves.

> You can also power machines from front panel but this is also bug and machines should not allow this.

And yet they conduct digilines on the front...

Also, we're forgetting that digilines also exists separate from cables, in particular digimese that conducts downwards.

**Comment by S-S-X** [comment]
> And yet they conduct digilines on the front...

Because that is one of default digiline connections but directly above and below are not, I've even written comment about that in technic digiline definition.

> Also, we're forgetting that digilines also exists separate from cables, in particular digimese that conducts downwards.

We are not forgetting that, it just is most common to have cables below machines and very uncommon to have cables above machines. This is partly due to how cables are supposed to work.

Basically for new connections below the machine was clearly safest option that made newly added digicables a lot more useful for connecting machines normal way.

**Pull request merged**
