### PR TITLE
Wrench rewrite

### PR DESCRIPTION
**Pull request by OgelGames**
Improves and fixes the wrench, making it suitable for all players.
- Inventory contents of nodes are now checked to prevent nesting inventories. (also an item blacklist)
- Wrench is now used with left-click instead of right-click. (allows repairing on anvil and putting in itemframes)
- Added chat messages for when nodes can't be picked up.
- Creative mode players can now place a picked-up node multiple times.
- Picked-up nodes can have custom descriptions. (added to technic chests and default signs)
- API now works, so other mods can register nodes.
- Extra nodes are no longer registered for supported nodes. (overrides `after_place_node`)

Also added support for digtron inventory nodes, and blacklisted loaded digtron crates.

### CODE REVIEW

**Comment by S-S-X** [comment]
> Wrench crafting setting has been removed, making it always craftable.

I do very strongly disagree with this, item is way too powerful for survival setting to be always craftable. That's also reason why recipe was removed.

**Comment by S-S-X** [comment]
Another thing to think about: using original nodes with meta will add little overhead to all node placements.
This might not be big thing alone but problem I see here is that after done once you cannot really remove that override ever and it becomes locked when wrench is enabled.

With most things this probably does not really matter other than having few relatively expensive calls but probably most people wont be placing a lot of wrench enabled nodes around or doing that with mesecons enabled devices while using mesecons_debug.

Those are corner cases that actually can become bit worse but biggest thing is locking it without any possible way to revert that node override. Something to think a bit first, I'd like to get bit more opinions specifically about this feature lock.

**Review by S-S-X — CHANGES_REQUESTED** [review]
Recipe enabled by default is something that should not be there in my opinion because item is way too powerful..

**Comment by OgelGames** [comment]
> biggest thing is locking it without any possible way to revert that node override. Something to think a bit first, I'd like to get bit more opinions specifically about this feature lock.

Huh? What do you mean by locking it?

**Comment by OgelGames** [comment]
> I do very strongly disagree with this, item is way too powerful for survival setting to be always craftable. 

I don't think it is, digtron crates and inventories already have the same functionality (carrying lots of items), and are even more powerful because there is no hard limit on how much can be put inside them.

> That's also reason why recipe was removed.

To be exact, it was because it allowed nesting of chests (see the comment added in https://github.com/mt-mods/technic/commit/0cf4133), which has now been fixed.

The recipe could be made more expensive though, it is very cheap currently.

**Comment by S-S-X** [comment]
> > problem I see here is that after done once you cannot really remove that override ever and it becomes locked when wrench is enabled ... I'd like to get bit more opinions specifically about this feature lock.
> 
> Huh? How is it locked?

How do you switch to another system if overriding node callbacks does not seem good? I think you cannot change it after introduced once while doing it any other way will leave options.

> I don't think it is, digtron crates and inventories already have the same functionality (carrying lots of items), and are even more powerful because there is no hard limit on how much can be put inside them. (and yes I know, that should be fixed too)

I'm not sure what you're telling here, idea is bad but can be added because other mod that does it should be also fixed?

**Comment by BuckarooBanzay** [comment]
> I do very strongly disagree with this, item is way too powerful for survival setting to be always craftable.

I like the idea of using that in survival mode :thinking: its not like you have a real advantage with this, aside from the mobile inventory

Pandorabox-related:
Can we at least do a trial run and see how players are ~~ab~~using it? Maybe with limited handouts (or presents?)

> The recipe could be made more expensive though, it is very cheap currently.

:+1:

**Comment by S-S-X** [comment]
> > I do very strongly disagree with this, item is way too powerful for survival setting to be always craftable.
> 
> I like the idea of using that in survival mode 🤔 its not like you have a real advantage with this, aside from the mobile inventory

I do think that inventory extensions like this are not good, you could add mod with some 20x bag capacity instead and it will not be as powerful as wrench, especially bad if added to existing games and servers without explicitly deciding to do so.
Wrench is still very useful admin tool for fixing some situations easily and forcing explicit configuration to disable it (after noticing that it was enabled) is not good in my opinion.

> Pandorabox-related: Can we at least do a trial run and see how players are ~ab~using it? Maybe with limited handouts (or presents?)

True that pandorabox survival mode is extremely easy survival, this is not situation with some other servers that do still have technic available.
This discussion can be moved to pandorabox.io with another pull request adding configuration for wrench.

**Comment by OgelGames** [comment]
> How do you switch to another system if overriding node callbacks does not seem good? I think you cannot change it after introduced once while doing it any other way will leave options.

Well yes, it would be complicated to change to another system (like a single item that changes texture), but I see no way to avoid that.

Overriding the callbacks isn't required though, it's just the most efficient way to do it. (the alternative is `minetest.register_on_placenode`)

> especially bad if added to existing games and servers without explicitly deciding to do so ... forcing explicit configuration to disable it (after noticing that it was enabled) is not good in my opinion

Hmm, maybe, considering there's be no recipe for over 7 years... 🤔 

> > I don't think it is, digtron crates and inventories already have the same functionality (carrying lots of items), and are even more powerful because there is no hard limit on how much can be put inside them. (and yes I know, that should be fixed too)
> 
> I'm not sure what you're telling here, idea is bad but can be added because other mod that does it should be also fixed?

I'm saying there has been a far more powerful item available in survival for a long time.

> I like the idea of using that in survival mode 🤔 its not like you have a real advantage with this, aside from the mobile inventory

👍

**Comment by S-S-X** [comment]
> but I see no way to avoid that.

Registering proxy item for wrench is way to do that.
User experience however would be a lot worse because of inventory image would be same for all picked up nodes and description would be only thing that indicates what item it actually is unless someone would implement https://github.com/minetest/minetest/issues/5686

**Comment by S-S-X** [comment]
It seems that server crashes if large container with items that contain a lot of metadata is dropped, can probably be prevented by adding more items to blacklist (any item picked up by wrench that can cause large metadata like signs).

**Comment by OgelGames** [comment]
> It seems that server crashes if large container with items that contain a lot of metadata is dropped, can probably be prevented by adding more items to blacklist (any item picked up by wrench that can cause large metadata like signs).

Could also do what digtron crate does, preventing dropping completely: https://github.com/minetest-mods/digtron/blob/master/nodes/node_crate.lua#L386

**Comment by S-S-X** [comment]
> Could also do what digtron crate does, preventing dropping completely: https://github.com/minetest-mods/digtron/blob/master/nodes/node_crate.lua#L386

You can still drop digtron crates... luckily many players have not sent their larger trons through tubes but there's factory setups for that @ pandorabox.

### For node placement callback I would like to still get some opinions/comments from other people.

It kind of is big thing because it is override that cannot be reverted afterwards, however bit easier now that crafting is not enabled by default as it decreases total amount of picked up nodes.

**Comment by S-S-X** [comment]
> Or check the size of the metadata and prevent dropping if it's too big.

I think this should probably be done when picking up node and prevent pickup is it would result in too large metadata.
This way you do not need to add workarounds for every mod that allows doing things that would cause crash because of too much metadata.

**Comment by S-S-X** [comment]
Related side note, I tried to hack up minetest/minetest#5686 and tested with `meta:set_string("inventory_image", "mod:nodename")`.
It works fine but  just for node names, I've got no knowledge about engine and implementation with more options would take much more time if I would do it (mostly to read and learn interfaces...).

I'm pretty sure someone with knowledge about engine itemdef/stack/inventory stuff could make it work in few minutes and also do proper complete implementation pretty fast. That would allow using proxy stack for wrench and some hope to get better UX in future.

However what I've seen happening around engine pull requests I'm pretty sure it has to be 1. probably just someone else 2. probably someone with engine knowledge 3. someone who can implement it fast enough to not waste too much time when pr is left unnoticed or rejected. 4. someone with a lot of extra time to debate / fix style / test / doc requests for PR.
Know someone? there would also be that bounty for it... I've just modified few lines in client/hud.cpp to make simple metadata texture switching work

**Comment by OgelGames** [comment]
> minetest/minetest#5686

There's another problem with that option: it would require the `min_minetest_version` to be whatever version that feature is added to.

Also, whichever system we change to will have the same problem of being hard to change again (or revert), because there will no longer be separate items to alias.

**Comment by S-S-X** [comment]
> > [minetest/minetest#5686](https://github.com/minetest/minetest/issues/5686)
> 
> There's another problem with that option: it would require the `min_minetest_version` to be whatever version that feature is added to.

That simply is not true, feature is fully backwards compatible and items will work completely fine with old clients.

> Also, whichever system we change to will have the same problem of being hard to change again (or revert), because there will no longer be separate items to alias.

It is not hard but close to impossible to remove additional (and most of time useless) processing from node callbacks of other nodes and other mods.
With proxy item that is not the case because you will not be overwriting code of other mods at all and there is no overrides to begin with.

**Comment by S-S-X** [comment]
Well, maybe I'm trying to protect other mods and special use cases bit too much here.

Actually to update wrench again to use single proxy item with good user experience and without affecting or overriding other mods is just destroying all items inside picked up containers and maybe for that it is enough to have note in changelog.

I guess admin should read changelog anyway, inform players and player who did not place their picked up containers in time will simply lose all items inside for not following advice.

**Comment by BuckarooBanzay** [comment]
> (still other opinions about this would be nice to have, I just see doing overrides as bad practice in general especially if causes troubles with future updates and in this case overrides could be completely avoided easily)

This is actually quite elegant in terms of up- and downgrading: An picked-up chest with the new method just becomes a regular chest if you downgrade, nothing to clean up afterwards.

IMO: i don't see an issue with it, there have been far worse hacks than this (not that i would describe this as a hack though)

**Review by BuckarooBanzay — APPROVED** [review]

**Pull request merged**
