### PR TITLE
Fix craft recipe warnings

### PR DESCRIPTION
**Pull request by OgelGames**
See https://github.com/mt-mods/technic/issues/175

### CODE REVIEW

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by BuckarooBanzay** [comment]
nice :+1:

**Comment by OgelGames** [comment]
Weird, seems like github is no longer setting the merge commit name to the PR name by default :/

**Comment by BuckarooBanzay** [comment]
> Weird, seems like github is no longer setting the merge commit name to the PR name by default :/

Oh, i just clicked through it :/ i'll adjust it next time if you want...

**Comment by S-S-X** [comment]
> Weird, seems like github is no longer setting the merge commit name to the PR name by default :/

It never did, only for squash because squash always creates new commit.

**Comment by BuckarooBanzay** [comment]
> It never did, only for squash because squash always creates new commit.

Strange, i thought i squashed it :/

This might explain it though:
Screenshot_2022-08-03_16-27-09

Turning this on now...

**Comment by S-S-X** [comment]
Hmm... I guess that's new and GitHub probably now either does squashing similar to git interactive rebase squas or wont really squash single commits when it is not necessary and there they actually changed default behavior instead of just adding configuration...

**Pull request merged**
