### PR TITLE
switching station nodetimer

### LINKED ISSUE #75: Use nodetimers on switching station

### LINKED ISSUE #109: Check and enable metadata cleanup LBM
PR #96 introduced LBM for metadata cleanup but left it completely disabled:
https://github.com/mt-mods/technic/blob/c89d0a1305ff6d0d07e153f92b008d86149f24a0/technic/machines/network.lua#L605-L636

This issue left here as reminder that such thing is available but cleanup is disabled, probably needs to be checked if it does remove all extra metadata that it should remove.
Also I think there's still many properties that should not be in node metadata but still gets stored into node metadata, could be good to collect all metadata setters and determine what is actually needed and what values could live in memory tables as well.

#106 and #108 might affect this too.

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
* uses nodetimer for the network activation
* kicks off the initial timer-start in the cleanup-lbm
* :warning: enables the `technic:metadata-cleanup` lbm

## Related

* closes #75
* closes #109

### CODE REVIEW

**Comment by S-S-X** [comment]
I think there was some LBM problem in engine, here: https://github.com/minetest/minetest/issues/4050
Should maybe try to find out more about that old issue if possible.

Could also check if #108 adds more keys for cleanup LBM as that was only partially implemented in #113, there's still those metadata read/update loops.

**Comment by BuckarooBanzay** [comment]
Maybe we should set `run_at_every_load = true` just in case
https://github.com/minetest/minetest/blob/627c22c36e32185d48d2faf8197e22cbaa4c50b2/doc/lua_api.txt#L7020

**Comment by S-S-X** [comment]
> Maybe we should set run_at_every_load = true just in case

Or just test how it goes without and turn that knob later if it seems that things do not work at all?

And do some preliminary testing on pandorabox test server? That would mostly require loading areas with networks and see if those networks get activated normally.

Also network inspection tool, if included for test server, could already pretty easily check if timeouts gets reset correctly when area is active but initial activation should already tell if it works or not.
Machines still have timeout ABM so those should also immediately tell if network is down and nodetimer does not work.

**Comment by BuckarooBanzay** [comment]
> Or just test how it goes without and turn that knob later if it seems that things do not work at all?

:+1: 

> And do some preliminary testing on pandorabox test server? That would mostly require loading areas with networks and see if those networks get activated normally.

I merged this branch on the test-server, haven't had time for anything else though (testing, etc) :/

> Also network inspection tool, if included for test server, could already pretty easily check if timeouts gets reset correctly when area is active but initial activation should already tell if it works or not.

That should already be in the latest `master` afaik...?

**Comment by S-S-X** [comment]
> > Also network inspection tool, if included for test server, could already pretty easily check if timeouts gets reset correctly when area is active but initial activation should already tell if it works or not.
>
> That should already be in the latest master afaik...?

Tool is not yet merged and no pull requests done yet as it was more for preview even while it actually also seemed to work just fine... those few things still needs some polishing.

Anyway there's machine timeout ABM and it should be enough to tell if node timers did not start as long as there's just single switching station in network (or if first one failed before activating second one).

What inspector would add then: Inspector could tell about timeout easily and through that it could tell if node timer for some other switching station in same network is not working correctly, that is nearly impossible to detect just with timeout ABM because you would have to wait until whole network times out.

Active network (switch cache flush) can also be cleared when next station gets activated, that should also reveal failed node timers.

**Comment by S-S-X** [comment]
@BuckarooBanzay could update this to test server, pulled latest stuff from master and checking if things work should be bit simpler  in game now that multimeter is also available.

**Comment by BuckarooBanzay** [comment]
done, updated to 2abccc503b6fdd72a95844f2e259496b78a70b77 and granted some privs :+1:

**Comment by S-S-X** [comment]
Checked total 91 networks, all seems to be working without problems.

**Review by OgelGames — APPROVED** [review]

**Pull request merged**
