### PR TITLE
Disable repair recipes for crystals and batteries

### PR DESCRIPTION
**Pull request by S-S-X**
Should probably test a bit, I've not done any testing.
Changes are simply based on Lua API documentation.

Also maybe test better how those actually behave in game before these changes, I've also not tested that at all.

### CODE REVIEW

**Comment by S-S-X** [comment]
> Huhhila: SX: Well batteries' one was actually working (but dunno why anyone would want to use it)

So for some reason before these changes repair recipe does not work for crystals but still does work for batteries...

**Comment by FeXoR-o-Illuria** [comment]
I tested and RC Batteries and Energy Crystals can no longer be crafted from 2 of the same kind.

**Comment by S-S-X** [comment]
> I tested and RC Batteries and Energy Crystals can no longer be crafted from 2 of the same kind.

Thanks, did you happen to test any normal functions like charging and discharging batteries / crystals?

After thinking about this a bit my opinion is that tool repair recipes should be disabled for batteries and energy crystals even if there would be some weird use case for these tool repair recipes.

Any sane use cases for these recipes if they would work correctly?

**Comment by FeXoR-o-Illuria** [comment]
Charging/discharging works as normal in HV Battery Box.
Jumpdrive increased EU capacity also works as usual.

**Review by BuckarooBanzay — APPROVED** [review]

**Pull request merged**
