### PR TITLE
Remove channel generators, switch nuclear reactor remote_channel to channel

### PR DESCRIPTION
**Pull request by S-S-X**
Removes digiline channel name generators.

Changed nuclear reactor digiline channel meta key from "remote_channel" _(never seen this used anywhere for digiline channels)_ to de facto standard channel meta key "channel".

Metadata is only updated when channel is actually set through formspec, always tries "remote_channel" first and use "channel" only if "remote_channel" is not set.
This is to keep maximum compatibility, LBM should be used to actually update channel metadata key everywhere.

For more information see #112

### CODE REVIEW

**Comment by OgelGames** [comment]
LGTM 👍 Also this will need to be updated: https://github.com/pandorabox-io/pandorabox_custom/blob/master/digi_copier_fixer.lua#L57-L58

**Comment by S-S-X** [comment]
> LGTM  Also this will need to be updated: https://github.com/pandorabox-io/pandorabox_custom/blob/master/digi_copier_fixer.lua#L57-L58

:+1: I was thinking if there's any mods depending on this remote_channel, seem like there is.

I think it would be good to change that to follow widely accepted "standards" _(rare thing for minetest mods...)_ but for backward compatibility it would also be possible to update "remote_channel" meta field when channel is changed, just not use it for reactor itself. So it would be there just for compatibility.

**Comment by S-S-X** [comment]
Updated to keep `remote_channel` but always try to use `channel` first.
Should be fine to merge.

**Review by OgelGames — APPROVED** [review]

**Comment by S-S-X** [comment]
I was not actually fully aware of this https://github.com/Desour/digiline_remote and had impression that digiline support was more like incomplete thing.
That explains why it was `remote_channel` and also to keep supporting digiline_remote mod `remote_channel` should remain there.
Added here: https://github.com/minetest-mods/technic/pull/341

Never used digiline_remote, should we also somehow test against things like that to better support other mods?

I believe most of real use testing happens on pandorabox but seems to be clear that this mod already has many other users too.

**Pull request merged**
