### PR TITLE
Updated the textureName for ethereal nodes

### PR DESCRIPTION
**Pull request by mightyjoe781**
added ethereal_  before each texture name according to new update from TenPlus1's Ethereal Mod

### CODE REVIEW

**Comment by OgelGames** [comment]
LGTM 👍

Also, this is new... 👀 
> **5 workflows awaiting approval**
> First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)

**Comment by S-S-X** [comment]
Mineunit failure to post comments seems to be explained here: https://github.com/actions/first-interaction/issues/10

**Comment by S-S-X** [comment]
Well, report still says
```
  ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●◌●●●●●
  57 successes / 0 failures / 0 errors / 1 pending : 0.16855 seconds
  
  Pending → spec/supply_converter_spec.lua @ 99
  Supply converter building overloads network
  spec/supply_converter_spec.lua:99: overload does not work with supply converter

Test coverage report for technic 9.66% in 10/102 files:
...
```
So ignore mineunit failure, tests are fine but posting comment about success failed 🤷

**Comment by OgelGames** [comment]
I don't see any reason not to merge this, so merging...

**Pull request merged**
