### PR TITLE
Network refactoring

### PR DESCRIPTION
**Pull request by S-S-X**
~~Depends on #230~~ Merged

### Main changes
* Network overload moved to `overload.lua`.
* Network building functions I've added during #96 moved to `network.lua`.
* Related to previous point, cables.lua cleaned up and contains only cable registration.
* Excluding tests there's 234 additions and 239 deletions in 4 files.

### Test updates
* Ignore sources outside technic directory for coverage report (cnc, worldgen).
* Adds digilines fixture for tests, basically makes tests execute code inside blocks that check if digilines mod is available.
* Reported coverage for technic mod is bit lower, this is expected because trechnic_worldgen code lines are not counted anymore.
* Reported CNC test coverage gets bit higher and this is expected because CNC technic tests were moved there.
* Regression test updates excluding mod code 16 files with 149 additions and 57 deletions.

There should be no functional changes in this branch, also this should not reduce available API functions.
This does however rename following functions and removes note about being exported only for tests:
```lua
-- NOTE: Exported for tests but should probably be moved to network.lua
technic.network_node_on_placenode = place_network_node
technic.network_node_on_dignode = remove_network_node
```
These are now renamed: `technic.place_network_node` and `technic.remove_network_node`.

### CODE REVIEW

**Comment by S-S-X** [comment]
Technic CNC tests could be also moved to technic_cnc/spec and make it load technic mod for tests that require technic.
Currently technic_cnc/spec contains only tests that can be executed without technic mod.
When moving keep CNC tests that do not depend on technic and just add another set for tests depending on technic.

**Comment by S-S-X** [comment]
Merged changes to tests into single commit... hopefully there's no need to revert those.

**Review by BuckarooBanzay — APPROVED** [review]
pulled this along with latest `master` in the test-server and turned on my factory: no issues so far, everything was as expected :+1:

**Comment by OgelGames** [comment]
Did some basic testing, only thing I noticed was that furnaces flicker on and off when they don't have power.

<details><summary><i>furnace flickering</i></summary>

technic-furnace-flicker
</details>

Everything else seems to work correctly 👍

**Comment by S-S-X** [comment]
> Did some basic testing, only thing I noticed was that furnaces flicker on and off when they don't have power. Everything else seems to work correctly 👍

Did you have something in input slot of machine? If not then this should not happen but if you had then it should be happening and always worked like that. (was added as feature for CNC machines too, visual alert about possible problem with machine that could do work but cannot start processing)

**Comment by S-S-X** [comment]
Flickering behavior was confirmed to be same on pandorabox and no other problems found so far I guess this is good enough so merging away. Been also waiting to be able to base latest work on master, makes everything simpler...

**Pull request merged**
