### PR TITLE
ES locale update

### PR DESCRIPTION
**Pull request by nonfreegithub**
spanish locale update and templates

### CODE REVIEW

**Comment by OgelGames** [comment]
Why is so much removed/changed? The template for `technic` in particular should not need to be changed, as it was updated in #289

**Comment by nonfreegithub** [comment]
> Why is so much removed/changed? The template for `technic` in particular should not need to be changed, as it was updated in #289

it was because I use [this built-in minetest script](https://github.com/minetest/minetest/pull/13739)

**Comment by OgelGames** [comment]
That explains why some translations are missing, that script doesn't pickup strings generated at runtime, such as the ones here: https://github.com/mt-mods/technic/blob/f1b99282e889e9a483c76af95ee3370b6d2b2d04/technic/machines/register/grinder_recipes.lua#L90-L132

**Comment by nonfreegithub** [comment]
ok, now I only update the technic.es.tr file

**Comment by S-S-X** [comment]
Should probably also be sorted like it was before. A lot of removed lines too, is that intentional?

**Comment by nonfreegithub** [comment]
> Should probably also be sorted like it was before. A lot of removed lines toois that intentional?

the [script](https://github.com/minetest/minetest/pull/13739) orders the lines, I think they were not removed, just ordered, this does not seem to affect the in-game translation

**Comment by S-S-X** [comment]
> the [script](https://github.com/minetest/minetest/pull/13739) orders the lines, I think they were not removed, just ordered, this does not seem to affect the in-game translation

There's 157 additions and 186 deletions in this change set. It is not just ordered but bad ordering does make it harder to quickly find out what has been removed. Few lines are comments with original author name but that still leaves over 20 missing lines.

**Comment by SwissalpS** [comment]
I agree with S-S-X and OgelGames, it's very hard to see what changed when the order is changed.

In a quick read through some parts I found multiple mistakes with capitalisation. In Spanish only proper names are capitalized. e.g. Names of people, places, countries. Not even weekdays and months are capitalized in Spanish, so words like "energia", "reactor nuclear" absolutely should not have capitals. (exceptions are tolerated when it's a title and every word is capitalized)

**Comment by nonfreegithub** [comment]
> In a quick read through some parts I found multiple mistakes with capitalisation. In Spanish only proper names are capitalized. e.g. Names of people, places, countries. Not even weekdays and months are capitalized in Spanish, so words like "energia", "reactor nuclear" absolutely should not have capitals. (exceptions are tolerated when it's a title and every word is capitalized)
> 
> Edit: I also feel the original author credits should be kept and amended with subsequent editors.

The capital letters were already in the original translation, I have not added them.

If I keep the name of the original author I must also add my name

**Comment by SwissalpS** [comment]
> If I keep the name of the original author I must also add my name

yes, you *may* add your real name but can also use any alias. It helps to show that changes have happened since original version.

>The capital letters were already in the original translation, I have not added them.

that is why keeping the order would help. But you may also change them while you are updating the file anyway ;)

**Comment by SwissalpS** [comment]
@nonfreegithub what is your plan? Submitting another clean PR or have you lost interrest?

**Pull request closed without merging**
