### PR TITLE
CNC Mk2

### LINKED ISSUE #149: CNC machine tube / upgrade support
Add tube and upgrade support for CNC machines, same as other technic machines: chest, CLU, battery.

This allows automating CNC processing and setting up protected public CNC machines.

New CNC machine will also have digiline support to set milling program and possibly (TBD) other functionality like disabling / enabling machine.

### PR DESCRIPTION
**Pull request by S-S-X**
Adds Technic CNC Mk2 machine with digiline, pipeworks and technic upgrade support.

Basic things working fine but some features still missing:
- [x] Formspec protection, chest upgrade should allow anyone to program
- [x] Formspec testing / chest upgrade testing
- [x] TBD what to do with `cnc_user` meta field
- [x] Add some basic mineunit tests
- [x] Documentation for digiline API
- [x] Backwards compatibility testing
- [x] 3 textures renamed and this causes issues with old CNC machines, I'd prefer not adding LBM if nothing else needs it
- [x] Add new textures for CNC Mk2
- [x] Pipeworks injectors do not work (other tube functions are fine). This is probably because of list name being dst.
- [x] CLU upgrade works while machine is active but does not do anything if machine is idle, reorder actions / checks.
- [x] TBD how to handle invalid materials, currently machines go into slow start/stop loop kind of alerting that something is wrong (similar what you see when furnace/grinder/etc inventory is clogged)
    * I think old behavior was simply do nothing, stay inactive? Did not verify.
    * What other machines do with incompatible items? Nothing?
    * **Ended up keeping on/off cycle but without full reset and only if program is selected**

Formspecs reworked completely, it is now easy to add paging for products if needed.
**Formspecs version is now 4, ~~this means that CNC will not be compatible with older Minetest clients.~~**

TBD, opinions welcome: Is breaking compatibility for old clients fine to do for next release?
edit. Launched 2 older versions for testing, 5.0.0 and 5.2.0, both seem usable. Not nice but usable and not exactly terrible (some mild overlapping and elements shifted a bit).

Closes #149

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
> TBD, opinions welcome: Is breaking compatibility for old clients fine to do for next release?

In which version were the formspec changes introduced? There should now be enough info in the logs to see (on pandorabox at least) how many players still with and old version join.

**Comment by S-S-X** [comment]
> > TBD, opinions welcome: Is breaking compatibility for old clients fine to do for next release?
> 
> In which version were the formspec changes introduced? There should now be enough info in the logs to see (on pandorabox at least) how many players still with and old version join.

I think 5.4 but not 100% sure, it is pretty hard to find information like that... change logs are mostly useless here because it seems those are written more for regular users, not for developers.

**Comment by OgelGames** [comment]
> **Formspecs version is now 4, this means that CNC will not be compatible with older Minetest clients.**
> TBD, opinions welcome: Is breaking compatibility for old clients fine to do for next release?

A better question would be, why does it even need to use version 4? Looking at the current code, I see no reason why it even needs to use more than version 1... 

```
* FORMSPEC VERSION 1:
  * (too much)
* FORMSPEC VERSION 2:
  * Forced real coordinates
  * background9[]: 9-slice scaling parameters
* FORMSPEC VERSION 3:
  * Formspec elements are drawn in the order of definition
  * bgcolor[]: use 3 parameters (bgcolor, formspec (now an enum), fbgcolor)
  * box[] and image[] elements enable clipping by default
  * new element: scroll_container[]
* FORMSPEC VERSION 4:
  * Allow dropdown indexing events
```
https://github.com/minetest/minetest/blob/c47313db65f968559711ac1b505ef341a9872017/doc/lua_api.txt#L2158-L2172

**Comment by S-S-X** [comment]
> A better question would be, why does it even need to use version 4?

Because latest version which is 4 does not change that much and I'd rather go latest possible that can be used than keep old versions around just to be sure that it is compatible with old software. True that version 3 would be fine too to allow easily adding some features but is there reason to use that instead of latest?

> Looking at the current code, I see no reason why it even needs to use more than version 1.

You can always add more stuff to formspecs like real_coordinates and use other hacks when needed but that is in my opinion very bad way to do things if you're aiming for new features.
If you do go for latest when changing things then you will have features available when changing it next time, if possible I would stay as up to date as possible without breaking compatibility too much.

If support for old versions will be dropped then also version 1 for sure will also be dropped first (mod api has dropped support for legacy stuff before and does that all the time).
When rebuilding something that relies on such API this is another important reason why I attempt to use latest possible and make it more likely to stay compatible as long as possible.
As concrete example, last change you did to CNC formspecs was fixing deprecated stuff.

You look at current code but that's not what you should look at, you should be looking at future code. Usually if code is as up to date as possible then it will be significantly easier to add new features on top of it.
For example there's a lot of formspec styling which becomes possible (actually works correctly) only with version 3 and I think some only with 4.

For these reasons I do think it would be better to test how broken it is with older clients instead of using legacy API just because it seems that latest functionality is not needed.
It might be possible to use latest, if it is I'd go with latest and only fall back to previous versions if there's really good reason to do so.

**Comment by OgelGames** [comment]
Makes sense :+1: Also, because it won't use any new stuff anyway, it should be compatible down to 5.1.0 (when the [`formspec_version_element`](https://github.com/minetest/minetest/blob/c47313db65f968559711ac1b505ef341a9872017/doc/lua_api.txt#L4472-L4473) feature was added).

Oh, and the next technic release will be 2.0.0, so some breaking changes are okay.

**Comment by S-S-X** [comment]
> Oh, and the next technic release will be 2.0.0, so some breaking changes are okay.

Yes, actually even last 1.2.0 were from old commits and 1.2.1 was backported fixes... with branches deleted it is already very hard to create any new feature releases for 1.x series...

Launched 2 older versions for testing, 5.0.0 and 5.2.0, both seem usable. Not nice but usable and not exactly terrible.

**Comment by S-S-X** [comment]
Some compatibility testing results:
* Old machines that were enabled before update will attempt to start production but fail, causes machine to switch between idle and active status. Consumes some power without doing anything. This is same state where new machines end up if incompatible stack is put into material slot.
* Old machines that are programmed after update work fine but formspec is not updated and therefore 3 textures for buttons are wrong, programming/production with those buttons however works just fine.
* 3 renamed textures fail screenshot_20210612_012704

To fix textures and bring programs up to date there could be simple upgrade function executed if machine has meta field `cnc_product`, this is not used with new machines. Instead of `cnc_product` new machines use simpler `program` meta field, value being simply selected program.

Upgrade could be triggered when formspec is submitted, this would cause old machines to attempt displaying wrong textures once but would be fixed after using machine once. This way LBM would not be needed because machines (formspecs) would be upgraded only when someone actually uses them.

Good enough? Maybe @OgelGames would have some better idea or does this sound good enough?

Another way could be symlinking old textures but while I think Minetest does do some deduplication for media this is not exactly nice thing to do because Windows does not handle symlinks that well and could cause problems if people are doing mod development on windows machines.

**Comment by OgelGames** [comment]
I think in this case it would make sense to upgrade them separately; to upgrade meta when running by checking for the old meta field, and upgrade formspec when it's closed/submitted.

**Comment by S-S-X** [comment]
I think this is ready for merge, anyone wants to try it out before merging? Test coverage is okayish at almost 80% so probably not many totally stupid mistakes but of course tests are only for very specific use cases.

Old machines are upgraded automatically if programmed and running (with automatic program data conversion) and through formspec submit if not yet programmed or not connected to technic network.

**Comment by OgelGames** [comment]
> anyone wants to try it out before merging?

Yes (me)

> * could later add flag to update formspec or queue update to be done on right click.

That's how I did it for beacons 👍

**Comment by OgelGames** [comment]
Seems to work as intended, didn't find any bugs 👍 

I also tested formspec with MT versions 5.0.0 - 5.4.0, and I think two changes could be made to improve compatibility with the older versions; add `real_coordinates[true]` to fix the sizing for 5.0.0 clients, and move the elements (upgrade slots, image of cnc, channel field) on the right side over slightly to fix the overlap for 5.1.0 - 5.3.0 clients. (it's even quite a small spacing with 5.4.0)

<details><summary>screenshots</summary>
5.0.0 client:

5 0 0_mk2

5.1.0 - 5.3.0 clients:

5 1 0_mk2

5.4.0 client:

5 4 0_mk2

</details>

**Comment by S-S-X** [comment]
Added `real_coordinates[true]` and adjusted digiline field a bit adding extra padding and making button slightly smaller.

**Comment by S-S-X** [comment]
Last few commits were mostly just simple formspec adjustments based on OgelGames's feedback and some more tests added.
I don't see reason to do extensive testing so merging this.

**Comment by BuckarooBanzay** [comment]
wow, nice work, looking forward to playing with that :+1:

**Pull request merged**
