### PR TITLE
convert zh_CN translations to UTF8

### PR DESCRIPTION
**Pull request by Niklp09**
Closes https://github.com/mt-mods/technic/issues/79

The ~~big5~~ **CP936** encoded translations trigger error messages on servers and clients. This doesn't happen anymore. I don't know if the translations make sense since I don't speak chinese :stuck_out_tongue:

### CODE REVIEW

**Comment by OgelGames** [comment]
I put a sample through the google translate test, the results were not promising...

Old translations on the left, new ones on the right. (some of the new ones didn't even translate)

image

I don't know if maybe something went wrong copypasting them, but something is definitly wrong.. :/

**Comment by Niklp09** [comment]
hmm I have no idea what went wrong, I used `iconv` to convert them...

**Comment by S-S-X** [comment]
Maybe you just got input charset wrong, see for example https://stackoverflow.com/questions/39946315/how-to-convert-a-big5-encoded-txt-file-to-utf8-encoded-txt-file

**Comment by OgelGames** [comment]
Weird... the fix is good, but when I look at "files changed" it still shows the bad ones? 😕

**Review by OgelGames — APPROVED** [review]

**Comment by S-S-X** [comment]
> Weird... the fix is good, but when I look at "files changed" it still shows the bad ones? I guess github's diff is confused ¯\_(ツ)_/¯

Same for me which is confusing, I'll see what git says about it... but I guess you're right and it is just some weird issue with github.

**Review by S-S-X — APPROVED** [review]
Looks good when comparing with git and ignoring github

**Pull request merged**
