### PR TITLE
Rewrite recipe code and add group support

### LINKED ISSUE #201: Machines don't support item groups
Hi there, I was attempting to extend my addon mod for this mod and I ran into a unclear issue. I cannot get grouped recipes to function on the compressor. 

Here is the exact recipe I was trying to add from my mod... 

> -- Compressor Recipes
> local recipes = {
> 	{"group:seed 8", "technic_addons:seedoil"},
> }
> for _, data in pairs(recipes) do
> 	technic.register_compressor_recipe({input = {data[1]}, output = data[2]})
> end

So the concern in question was "group:seed". 

Is it entirely possible to have this resolved please? 

Thanks in advance. :)

### PR DESCRIPTION
**Pull request by OgelGames**
Rewrite of recipe code to fix some issues and add new features. (sorry this took so long)

- Recipes now support groups (for input items)
- All recipes used by technic machines (including `cooking` recipes) are now cached for performance.
- Recipes are now processed and cached immediately after mod loading.

Fixes #201, and the issues discussed in #328 and #335.

@nonfreegithub @ThePython10110

### CODE REVIEW

**Comment by OgelGames** [comment]
Hmm, something seems to have broken mineunit 👀 
```
Failure → spec/lv_network_spec.lua @ 122
LV machine network smelts ores
Failure → spec/lv_network_spec.lua @ 132
LV machine network grinds ores
Failure → spec/lv_network_spec.lua @ 142
LV machine network comperess sand
```
I tested these in-game and they work as normal.

**Review by BuckarooBanzay — APPROVED** [review]
didn't test but code looks sane enough (not sure about the mineunit tests though :/ )

**Comment by S-S-X** [comment]
Basically Mineunit isn't approving this:
```lua
table.insert(minetest.registered_on_mods_loaded, 1, cache_all_recipes)
```

This was one of those things where I wanted to add clear errors and requirement for explicit configuration to allow questionable things. Currently results are still mixed: some stuff has clear `assert`s, some is fully protected, some logs warnings and some is permissive.

Fixtures can be used and in other projects have been used to patch similar things but personally I'd recommend against it.

In this case, instead of silently adding required features through fixtures, I'd vote for some public shaming and pointing the finger at Mineunit until fixed.

**Comment by OgelGames** [comment]
Tested this again, everything seems to be working correctly, so I think this is safe to merge.

**Pull request merged**
