### PR TITLE
Alias wrench legacy nodes

### LINKED ISSUE #245: Add aliases for old wrench node names
See https://github.com/pandorabox-io/pandorabox-mods/pull/1962
And #242

Basically add some legacy.lua with aliases for old wrench picked up nodes.

Also @OgelGames if you were going to actually fix wrench, maybe resolve aliases for new pickups instead of using whatever was given when node was registered...

### PR DESCRIPTION
**Pull request by S-S-X**
Fixes #245 

Additionally I'd like to also add note here, imo in future wrench should not be registering any new nodes but just single item.

### CODE REVIEW

**Comment by S-S-X** [comment]
Managed to push c06dae6 without changing anything...

**Comment by S-S-X** [comment]
Actually not sure about this, it seems that some nodes were not actually possible to pick up even while those are registered.
Very old aliases should probably be removed from tests.

wooden sign from default is probably only thing that might still be around, maybe.

**Comment by BuckarooBanzay** [comment]
> It might be better to just forget about these, all technic nodes are from older legacy.lua and these aliases were added around 8 years ago.

Works for me :+1:

**Comment by S-S-X** [comment]
Alias default:sign_wall was also added 6 years ago and probably not needed for wrench anymore.
No idea when it was released with engine but probably at least 5 years ago.

Closing this PR as useless, adding aliases that most likely are not needed anywhere.

**Pull request closed without merging**
