### PR TITLE
Update registration functions for technic

### LINKED ISSUE #117: Rewrite all machine/cable registration functions to have generic format
Also see #115 comments.

This would be very good thing for both technic mod itself and for other mods that like to use API functions provided by technic mods.
Currently there's not yet too many mods around using technic API, at least not publicly visible, I was digging large part of internet few months ago looking for these and found just few.
However with good enough API there would be a lot of potential for external mods implementing more machines / cables / something.

Currently API is not that good for external use and could be significantly improved for internal use to reduce code and make parameters and naming uniform.

Currently naming seems to mostly follow some unwritten guidelines so it should be possible to just implement API helpers and remove extra code. Might require renaming some things (textures mostly).

### PR DESCRIPTION
**Pull request by S-S-X**
Closes #117 

Changes excluding tests: https://github.com/mt-mods/technic/compare/master...ecea17ec9979a4e0b6a0ac4d3298398175f6c136

### API

Updates machine and cable registration API to follow signature of `minetest.register_node` function.
Allows registering from different mod and setting any mod name for nodes.
Updates cable plate placement to use actual math instead of weird lookup tables.
Reduces hard coded data in core source files.
Reduces nested registration wrappers.

- [x] Test cable plate placement using machines and tools.
    * Either one time manual test or automated tests, does not really matter.
- [x] Test for registrations with different mod name and different current mod name reported by engine.
    * Should be automated test to allow verifying API compatibility.

### List of updated registration functions
* New signature: `function technic.register_base_machine(name, def)`
    * Was: `function technic.register_base_machine(data)`
* New signature: `function technic.register_solar_array(name, def)`
    * Was: `function technic.register_solar_array(data)`
* New signature: `function technic.register_battery_box(name, def)`
    * Was: `function technic.register_battery_box(data)`
* New signature: `function technic.register_cable(nodename, data)`
    * Was: `function technic.register_cable(tier, size, description, prefix, override_cable, override_cable_plate)`
    * It was not possible to easily use these outside of technic mod, there should not be any conflicts.
* New function: `function technic.register_cable_plate(nodename, data)`
    * Cable plates were always registered through `technic.register_cable`, added new function for this.
    * It was not possible to easily use these outside of technic mod, there should not be any conflicts.

### Compatibility
* Machine registration API follows `minetest.register_node` interface:
* Machine registration is compatible with old style interface
    * see [technic/machines/compat/api.lua](https://github.com/mt-mods/technic/blob/issue-117/technic/machines/compat/api.lua)
    * Logs warning message when old function signature is used. Data is upgraded and machine registered.
    * Does not modify input data, for some parts this is different from previous implementation.
    * Can be changed to modify input data for very small performance increase. However I don't see this being important at all for registration (server startup time), difference is very small and makes API usage harder.
* Old machine registration wrappers moved to technic/machines/compat/api.lua:
    * `function technic.register_alloy_furnace(def)`
    * `function technic.register_centrifuge(def)`
    * `function technic.register_compressor(def)`
    * `function technic.register_extractor(def)`
    * `function technic.register_freezer(def)`
    * `function technic.register_grinder(def)`
    * `function technic.register_electric_furnace(def)`
    - [x] Register these directly without using wrappers.
    - [x] Add warning logging if functions are used.

There's another branch to do similar with chests, usable starting point with working API interface but incomplete implementation.

### CODE REVIEW

**Comment by OgelGames** [comment]
I think the node name should be not altered at all (besides `_active`, etc. suffixes) for any of the machines.

As for the name changes, I'm all for consistency, so 👍 (I've searched for "hv_solar" way too many times...)

**Comment by S-S-X** [comment]
> I think the node name should be not altered at all (besides `_active`, etc. suffixes) for any of the machines.

There's no other changes to actual node names so far, commits to remove tier is just to make caller responsible for adding tier. Inside Technic those tier parts are just moved up one level up to allow free form node names.

Simply put only change to node naming so far is:
Names like `technic:solar_array_mv` becomes `technic:mv_solar_array` for all solar arrays.
Aliases like `minetest.register_alias("technic:solar_array_mv", "technic:mv_solar_array")` are added for all solar arrays.

**Comment by S-S-X** [comment]
Basic automated registration tests done, however part of tests are currently disabled for base machine and battery box because all fields are not yet available through definition table.
Basic API interface however is done and rest of it should be mostly added feature instead of breaking changes.

**Comment by S-S-X** [comment]
Removed WIP label as I think merging this should be decided before continuing to work on actual API features.

Changes are fairly big and some testing is needed, I've however tested this against extended-tests branch and there it passed every test case just fine.
There's however no verification if all builtin machines are actually still registered or if I managed to remove some...

**Review by OgelGames — APPROVED** [review]
Did some basic testing, checking the chests were the same, and also testing registering a chest from another mod, all seems to be working 👍

**Comment by S-S-X** [comment]
Merged master branch (extended-tests) and cleaned up commits a bit, will do another iteration later for commits that have mixed up code and tests.

**Comment by S-S-X** [comment]
If there's no objections I think I'll be merging this one soon.

I'll add few simple tests for overload and API to this branch before that, very soon.

Also @BuckarooBanzay opinion about renaming solar array nodes to follow style of texture names and other machine names: _technic:solar_array_mv_ becomes _technic:mv_solar_array_ and similar for lv and hv other solar arrays.
If that feels like bad idea it can be removed easily from this PR and even keep common style for automatic texture naming.

Started working on refactoring network and registration stuff on top of this change few days ago, mostly fixing TODO notes I've left when rewriting core network code on #96

**Comment by S-S-X** [comment]
Cleaned up debug prints and rebased...

**Comment by S-S-X** [comment]
Tested placement using machines a bit: Constructor and deployer works fine, replacer however seems to be broken.

**Comment by SwissalpS** [comment]
> Tested placement using machines a bit: Constructor and deployer works fine, replacer however seems to be broken.

replacer has not worked for cable plates because they don't use param values. Replacer only stores item name, param and param2.

**Comment by S-S-X** [comment]
Did some little play testing, jumpdrive and space cannons were fine so machine registration compatibility is tested. Screwdriver was not fine with cable plates because for some reason I had `paramtype2 = "facedir"`, fixed that.

**Review by OgelGames — APPROVED** [review]
Hard to check every line of code, but looking at the main changes, everything seems to be good 👍 

I also loaded a world with the `pandorabox_integration_test` enabled, it didn't complain about anything either :)

**Pull request merged**
