### PR TITLE
Use moreores tin when moreores and mcl_core are detected

### PR DESCRIPTION
**Pull request by programmerjake**
Fixes: #381

### CODE REVIEW

**Comment by OgelGames** [comment]
We really should switch to using [`xcompat`](https://github.com/mt-mods/xcompat), but I see no reason not to add this small change in the meantime :+1:

**Review by OgelGames — APPROVED** [review]

**Review by OgelGames — DISMISSED** [review]

**Comment by OgelGames** [comment]
Actually now that I look a bit closer, you should add the changes to lines 17 and 18, like this:
```lua
	tin_ingot = has_moreores and "moreores:tin_ingot" or has_mcl and "mcl_core:iron_ingot" or "default:tin_ingot",
	tin_lump = has_moreores and "moreores:tin_lump" or has_mcl and "mcl_raw_ores:raw_iron" or "default:tin_lump",
```

**Comment by programmerjake** [comment]
> Actually now that I look a bit closer, you should add the changes to lines 17 and 18, like this:
> 
> ```lua
> 	tin_ingot = has_moreores and "moreores:tin_ingot" or has_mcl and "mcl_core:iron_ingot" or "default:tin_ingot",
> 	tin_lump = has_moreores and "moreores:tin_lump" or has_mcl and "mcl_raw_ores:raw_iron" or "default:tin_lump",
> ```

no, because you need `default:tin_*` even if you have `moreores`. so I thought that would make the boolean expression too complex, so I used a much easier to understand `if`

**Comment by programmerjake** [comment]
|&nbsp;| without moreores | with moreores |
|-|-|-|
|minetest game|default's tin|default's tin|
|mineclone\*|mineclone's iron|moreores's tin|

**Comment by OgelGames** [comment]
Oh, right... because moreores doesn't register its tin when default tin is available 🤦

**Review by OgelGames — APPROVED** [review]

**Pull request merged**
