### PR TITLE
refactor integration tests

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
* removed unused workflows
* refactored integration-tests to use [mtt](https://github.com/buckarooBanzay/mtt)
* added engine versions `5.3.0`, `5.4.0`, `5.5.0` and `latest` to test matrix
* added mapgen smoketest
* added nodename check with existing list of `technic*` nodes
* enabled `deprecated_lua_api_handling = error` to catch deprecated calls

**note**: integrations-tests _should_ not overlap with the mineunit-tests

### CODE REVIEW

**Review by S-S-X — COMMENTED** [review]
Everything else looks good to me but not sure about this:
Should integration tests use its own mod.conf / edit existing to inject mtt dependency instead of having it in release mod.conf?

Reason why I'm asking is that optional_depends is kind of advertisement for compatible game content and I've seen some player just installing all they see in dependency lists and are able to get.

But mtt is meant to be developer tool instead of content for players so should it be hidden from release dependency list?
I think another possible way to explain mtt to players would be to show detailed mtt information formspec / some other message about mtt when joining game (handled by mtt mod)?

**Review by S-S-X — APPROVED** [review]
Noted that mtt requires user to turn on minetest.conf switch before actually doing anything?
I guess in that case it is not that bad to have it in dependency list so approving this anyway.

**Comment by OgelGames** [comment]
The `mtt` optional dependency can be avoided by using `minetest.register_on_mods_loaded` in `integration_test.lua`.

**Comment by BuckarooBanzay** [comment]
>  Should integration tests use its own mod.conf / edit existing to inject mtt dependency instead of having it in release mod.conf?

The `mtt` mod is an inert component if not properly configured and only exposes its api in that case (to not crash anything).

> But mtt is meant to be developer tool instead of content for players so should it be hidden from release dependency list?

I'm planning to upload the mod to the cdb, not for the players but to satisfy some hard-dependencies in games (and to reserve the name of course)
But yeah: it is not intended for casual players but also doesn't get in the way :shrug: 

> The mtt optional dependency can be avoided by using minetest.register_on_mods_loaded in integration_test.lua.

Interesting, completely forgot i could do that, i'll look into that :+1:

**Comment by BuckarooBanzay** [comment]
> The mtt optional dependency can be avoided by using minetest.register_on_mods_loaded in integration_test.lua.

_sigh_, looks like `minetest.get_current_modname()` doesn't work in the mods_loaded callback :unamused:

The modname is used to optionally filter mods from testing and to test only what's needed (note: there is no other mod with tests in the dependency tree but if there was it could be filtered out with `mtt_filter = technic` in the settings)

**Comment by BuckarooBanzay** [comment]
also added `deprecated_lua_api_handling = error` to catch legacy api-calls

**Pull request merged**
