### PR TITLE
Adding a new Recipe for the Extractor

### PR DESCRIPTION
**Pull request by OAKO-UCONN**
Garlic will create White Dye when put in an extractor.

### CODE REVIEW

**Comment by S-S-X** [comment]
Is clove / whole recipes mixed up perhaps?
In current proposal clove gives 8 white dye and whole gives 1 white dye.
8 dye for clove is bit much imo, I think 4 would be better for cloves and maybe also bit higher for whole like 4, 6 or even 8 would work (garlic gives 8 cloves).

**Comment by OgelGames** [comment]
I think it should be something like 1 or 2 dye from whole garlic only, because I don't see how garlic should give white dye at all, would make more sense for it to give brown dye if any...

**Comment by S-S-X** [comment]
https://pubmed.ncbi.nlm.nih.gov/25401128/

**Comment by OgelGames** [comment]
Interesting... Still shouldn't give much dye though.

**Pull request closed without merging**
